---
defaultStorageEngineId: "mongodb"
logLevel: info
# For OpenCGA installation: org.opencb.opencga.analysis.storage.CatalogStudyConfigurationManager
studyMetadataManager: "${OPENCGA.STORAGE.STUDY.METADATA.MANAGER}"
cellbase:
  hosts:
  - "${OPENCGA.CELLBASE.HOST}"
  version: "${OPENCGA.CELLBASE.VERSION}"
storageEngines:
- id: "mongodb"
  options: {}
  alignment:
    manager: "org.opencb.opencga.storage.mongodb.alignment.MongoDBAlignmentStorageManager"
    options:
      database.name: "opencga"
      tools.samtools: "${OPENCGA.INSTALLATION.DIR}/tools/samtools/samtools"
      transform.region_size: 200000
      transform.coverage_chunk_size: 1000
      mean_coverage_size_list: [200, 10000]
    database:
      hosts:
      - "${OPENCGA.STORAGE.ALIGNMENT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.ALIGNMENT.DB.USER}"
      password: "${OPENCGA.STORAGE.ALIGNMENT.DB.PASSWORD}"
  variant:
    manager: "org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager"
    options:
      database.name: "opencga"
      collection.variants: "variants"
      collection.studies: "studies"
      include.stats: false
      annotator: cellbase_rest
      species: "hsapiens"
      assembly: "GRCh37"
      transform.batch_size: 200
      transform.threads: 4
      load.batch_size: 100
      load.bulk_size: 100
      load.compress_genotypes: true
      load.threads: 4
      authentication.db: ${OPENCGA.STORAGE.VARIANT.DB.AUTHENTICATION_DATABASE}
      ## To delete:
      include.genotypes: true
      include.src: false
      collection.files: "files"
    database:
      hosts:
      - "${OPENCGA.STORAGE.VARIANT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.VARIANT.DB.USER}"
      password: "${OPENCGA.STORAGE.VARIANT.DB.PASSWORD}"
- id: "hadoop"
  options: {}
  alignment:
    manager: "org.opencb.opencga.storage.hadoop.alignment.MongoDBAlignmentStorageManager"
    options: {}
    database:
      hosts:
      - "who-master:60000"
      user: "user"
      password: "password"
  variant:
    manager: "org.opencb.opencga.storage.hadoop.variant.MongoDBVariantStorageManager"
    options: {}
    database:
      hosts:
      - "who-master:60000"
      user: "user"
      password: "password"
