---
defaultStorageEngineId: "${OPENCGA.STORAGE.ENGINE.DEFAULT}"
logLevel: "info"
logFile: ""

## This value can be set up using maven profiles in your .m2/settings.xml
studyMetadataManager: "${OPENCGA.STORAGE.STUDY.METADATA.MANAGER}"

## CellBase client configuration, this is used mainly when annotating variants
## This can be set up using maven profiles in your .m2/settings.xml
cellbase:
  hosts:      ## 'remote' URL hosts to annotate variants, for example: http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/
  - "${OPENCGA.CELLBASE.HOST}"
  version: "${OPENCGA.CELLBASE.VERSION}"
  database:   ## 'local' connection to CellBase MongoDB
    hosts:
    - ""
    user: ""
    password: ""
    options: {}         ## This is intended for database specific options such as --authenticationDatabase in MongoDB
  preferred: "remote"   ## This accept two values: 'local' and 'remote' to fetch data

## Storage Query Server configuration. When CLI is launched in 'server' mode a RESTful web server
## is launched in the specified port. Only authorized hosts are allowed to query data.
server:
  rest: 9090
  grpc: 9091
  authManager: "org.opencb.opencga.storage.server.common.DefaultAuthManager"       ## Path to the AuthManager implementation class
  storageEngine: "mongodb"
  authorizedHosts: ["0.0.0.0"]
  options: {}

benchmark:
  storageEngine: "mongodb"
  numRepetitions: 3
  load: false
  queries: ["count", "distinct"]
  databaseName: "opencga"
  table: "variants"
  concurrency: 1
  database:   ## 'local' connection to CellBase MongoDB
      hosts:
      - "localhost:27017"
      user: ""
      password: ""
      options: {}         ## This is intended for database specific options such as --authenticationDatabase in MongoDB

## The following section defines all availables storage engine plugins installed
## Default plugin is 'mongodb' storage engine
storageEngines:
- id: "mongodb"
  options: {}     ## this field is intended to be removed, try not to use it.
  alignment:
    manager: "org.opencb.opencga.storage.mongodb.alignment.MongoDBAlignmentStorageManager"
    options:
      database.name: "opencga"
      tools.samtools: "${OPENCGA.INSTALLATION.DIR}/tools/samtools/samtools"
      transform.region_size: 200000
      transform.coverage_chunk_size: 1000
      mean_coverage_size_list: [200, 10000]
    database:
      hosts:
      - "${OPENCGA.STORAGE.ALIGNMENT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.ALIGNMENT.DB.USER}"
      password: "${OPENCGA.STORAGE.ALIGNMENT.DB.PASSWORD}"
  variant:
    manager: "org.opencb.opencga.storage.mongodb.variant.MongoDBVariantStorageManager"
    options:
      database.name: "opencga"
      collection.variants: "variants"
      collection.studies: "studies"
      include.stats: false
      annotator: cellbase_rest
      species: "hsapiens"
      assembly: "GRCh37"
      transform.batch_size: 200
      transform.threads: 4
      load.batch_size: 100
      load.bulk_size: 100
      load.compress_genotypes: true
      load.threads: 4
      authentication.db: ${OPENCGA.STORAGE.VARIANT.DB.AUTHENTICATION_DATABASE}
      ## To delete:
      include.genotypes: true
      include.src: false
      collection.files: "files"
    database:
      hosts:
      - "${OPENCGA.STORAGE.VARIANT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.VARIANT.DB.USER}"
      password: "${OPENCGA.STORAGE.VARIANT.DB.PASSWORD}"

## For using this plugin you need to have a Hadoop cluster and run the CLI from a well configured Hadoop client
- id: "hadoop"
  options: {}
  alignment:
    manager: "org.opencb.opencga.storage.hadoop.alignment.MongoDBAlignmentStorageManager"
    options:
      fs.defaultFS: "${OPENCGA.STORAGE.HADOOP.HDFS.DEFAULT_FS}"
    database:
      hosts:
      - "${OPENCGA.STORAGE.VARIANT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.VARIANT.DB.USER}"
      password: "${OPENCGA.STORAGE.VARIANT.DB.PASSWORD}"
  variant:
    manager: "org.opencb.opencga.storage.hadoop.variant.HadoopVariantStorageManager"
    options:
      #Generic options
      database.name: "opencga"
      annotator: cellbase_rest
      species: "hsapiens"
      assembly: "GRCh37"
      #Plugin specific options
      hadoop.bin: "hadoop"
      hadoop.env: "HADOOP_USER_CLASSPATH_FIRST=true,HADOOP_CLASSPATH=${OPENCGA.INSTALLATION.DIR}/libs/protobuf-java-3.0.0-beta-1.jar"
      opencga.storage.hadoop.jar-with-dependencies: "${OPENCGA.INSTALLATION.DIR}/opencga-storage-hadoop-${opencga.version}-jar-with-dependencies.jar"
      fs.defaultFS: "${OPENCGA.STORAGE.HADOOP.HDFS.DEFAULT_FS}"
    database:
      hosts:
      - "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.HOSTS}"
      user: "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.USER}"
      password: "${OPENCGA.STORAGE.HADOOP.VARIANT.DB.PASSWORD}"
